<?php

namespace Database\Seeders;

use App\Models\Genre;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class GenreSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $genres = [
            ['name' => 'Pop'],
            ['name' => 'Rock'],
            ['name' => 'Jazz'],
            ['name' => 'Classical'],
            ['name' => 'Hip-Hop'],
            ['name' => 'R&B'],
            ['name' => 'Country'],
            ['name' => 'Electronic'],
            ['name' => 'Reggae'],
            ['name' => 'Blues'],
            ['name' => 'Soul'],
            ['name' => 'Folk'],
            ['name' => 'Punk'],
            ['name' => 'Metal'],
            ['name' => 'Alternative'],
            ['name' => 'Indie'],
            ['name' => 'Disco'],
            ['name' => 'Techno'],
            ['name' => 'House'],
            ['name' => 'Trance'],
            ['name' => 'Dubstep'],
            ['name' => 'Ambient'],
            ['name' => 'World Music'],
            ['name' => 'Reggaeton'],
            ['name' => 'Ska'],
            ['name' => 'Gospel'],
            ['name' => 'Latin'],
            ['name' => 'Funk'],
            ['name' => 'New Age'],
            ['name' => 'Salsa'],
            ['name' => 'K-pop'],
            ['name' => 'Soundtrack'],
            ['name' => 'Bluegrass'],
            ['name' => 'Grunge'],
            ['name' => 'Garage Rock'],
            ['name' => 'Experimental'],
            ['name' => 'Progressive Rock'],
            ['name' => 'Trap'],
            ['name' => 'Dub'],
            ['name' => 'Synthwave'],
            ['name' => 'Electropop'],
            ['name' => 'Industrial'],
            ['name' => 'Lo-fi'],
            ['name' => 'Post-rock'],
            ['name' => 'Synthpop'],
            ['name' => 'Shoegaze'],
            ['name' => 'Hardcore'],
            ['name' => 'Post-punk'],
            ['name' => 'Screamo'],
            ['name' => 'Folk Rock'],
            ['name' => 'Baroque'],
            ['name' => 'Celtic'],
            ['name' => 'Afrobeat'],
            ['name' => 'Cumbia'],
            ['name' => 'Tango'],
            ['name' => 'Bossa Nova'],
            ['name' => 'Chillout'],
            ['name' => 'Ambient House'],
            ['name' => 'Dancehall'],
            ['name' => 'Acapella'],
            ['name' => 'Musical Theatre'],
            ['name' => 'Tech House'],
            ['name' => 'Tribal House'],
            ['name' => 'Reggae Fusion'],
            ['name' => 'Rap'],
            ['name' => 'Glam Rock'],
            ['name' => 'Hard Rock'],
            ['name' => 'Progressive Metal'],
            ['name' => 'Post-hardcore'],
            ['name' => 'Death Metal'],
            ['name' => 'Black Metal'],
            ['name' => 'Thrash Metal'],
            ['name' => 'Doom Metal'],
            ['name' => 'Symphonic Metal'],
            ['name' => 'Speed Metal'],
            ['name' => 'Power Metal'],
            ['name' => 'Sludge Metal'],
            ['name' => 'Melodic Metal'],
            ['name' => 'Industrial Metal'],
            ['name' => 'Jazz Fusion'],
            ['name' => 'Folk Metal'],
            ['name' => 'Blues Rock'],
            ['name' => 'Boogie Woogie'],
            ['name' => 'Traditional Pop'],
            ['name' => 'Big Band'],
            ['name' => 'Barbershop'],
            ['name' => 'Chamber Music'],
            ['name' => 'Choro'],
            ['name' => 'Zydeco'],
            ['name' => 'Psychedelic Rock'],
            ['name' => 'Neo-Soul'],
            ['name' => 'Folk-Pop'],
            ['name' => 'Eurodance'],
            ['name' => 'J-Pop'],
            ['name' => 'Celtic Folk'],
            ['name' => 'Acid Jazz'],
            ['name' => 'Vocal Jazz'],
            ['name' => 'Funk Rock'],
            ['name' => 'Synthpop'],
            ['name' => 'Indie Pop'],
            ['name' => 'Synthwave'],
            ['name' => 'Psytrance'],
            ['name' => 'Chiptune'],
            ['name' => 'Industrial Rock'],
            ['name' => 'Neo-Classical'],
            ['name' => 'Tribal'],
            ['name' => 'Hi-NRG'],
            ['name' => 'Freestyle'],
            ['name' => 'Experimental Rock'],
            ['name' => 'Minimal Techno'],
            ['name' => 'Deep House'],
            ['name' => 'Electronica'],
            ['name' => 'Hardstyle'],
            ['name' => 'Future Bass'],
            ['name' => 'Techno Trance'],
        ];

        foreach ($genres as $genre) {
            Genre::create($genre);
        }

    }
}
